# CMake file for HMPLC Core2350

list(APPEND PICO_BOARD_HEADER_DIRS ${MICROPY_BOARD_DIR})
set(PICO_BOARD "hmplc_core2350")
set(PICO_PLATFORM "rp2350")

# Required at the cmake level since the rp2 port no longer defaults it.
set(PICO_FLASH_SIZE_BYTES 4194304)

if(NOT DEFINED MICROPY_HW_FLASH_STORAGE_BYTES)
    set(MICROPY_HW_FLASH_STORAGE_BYTES 3145728)  # 3 * 1024 * 1024
endif()

# 8MB PSRAM on GPIO7.
set(MICROPY_HW_ENABLE_PSRAM 1)
set(MICROPY_HW_PSRAM_CS_PIN 7)
